package snpclip;

import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import java.awt.Dimension;
import javax.swing.JViewport;
import java.awt.Color;
import java.util.BitSet;

public class ResultPanel extends javax.swing.JPanel {

    // Variables declaration - do not modify
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration

    DefaultTableModel dm = new DefaultTableModel();
    Vector columnname = new Vector();
    String liststring[] = {"SNP Count", "Sample Size"};
    int NumSNPs = 0;
    double Percent = 0.0;

    BitSet FI;

    /** Creates new form ResultPanel */
    public ResultPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents() {
        CenterPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        setLayout(new java.awt.BorderLayout());

        CenterPanel.setLayout(new java.awt.BorderLayout());
        CenterPanel.setPreferredSize(new java.awt.Dimension(150, 150));
        CenterPanel.setMinimumSize(new java.awt.Dimension(150, 150));

        CenterPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        columnname.add("Item");
        columnname.add("Value");
        jTable1.setModel(dm);

        jScrollPane1.setViewportView(jTable1);


        JViewport jvp = new JViewport();
        RowNumberHeader rh = new RowNumberHeader(jTable1);
        jvp.setView(rh);
        jScrollPane1.setRowHeader(jvp);

        CenterPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTable1.setBackground(Color.white);
        jScrollPane1.setBackground(Color.white);
        rh.setBackground(Color.white);

        add(CenterPanel, java.awt.BorderLayout.CENTER);

    }// </editor-fold>

    void setResultTable(Vector data) {
        dm.setDataVector(data, columnname);
    }

    void setFilter(BitSet fi)
    {
        FI = fi;
    }

}
