package snpclip;
import java.util.BitSet;
import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.SwingUtilities;

public class TransposeDialog extends javax.swing.JDialog {
    public int Trans = -1;
    public String init_dit = new String();

    /** Creates new form TranposeDialog */
    public TransposeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setTitle("File Export Dialog");
        initComponents();
         String os_type = System.getProperty("os.name");
         if (os_type.indexOf("Windows") >= 0) {
             init_dit = System.getProperty("user.dir") + System.getProperty("file.separator");
         }
         else {
             init_dit = System.getProperty("user.home") + System.getProperty("file.separator");
         }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("S.A.G.E. Format (SNPs by column)");

        jLabel1.setText("Please Choose an Output Format:");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Affymetrix Format (SNPs by row)");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Provide Both Files");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
    }
});


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3))))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
            if(jRadioButton1.isSelected())
                 {
                     Trans = 0; //SAGE
                 }
                 else if (jRadioButton2.isSelected())
                 {
                     Trans = 1;//BY ROW
                 }
                 else if(jRadioButton3.isSelected())
                 {
                     Trans = 2;//BOTH
                 }
                 this.setVisible(false);
                 JFileChooser jFileChooser1 = new JFileChooser();
                 jFileChooser1.setCurrentDirectory(new File(init_dit));

                 jFileChooser1.showSaveDialog(this);
                 MainFrame.mainFrame1.filePath = jFileChooser1.getSelectedFile().getPath();
                 MainFrame.mainFrame1.fileName = jFileChooser1.getSelectedFile().getName();
                 MainFrame.mainFrame1.SetProgress(0);
                 String name = "";
                 String extension = "";
                 String parentdir = "";
                 if (MainFrame.mainFrame1.fileName.indexOf(".") > 0) {
                     name = MainFrame.mainFrame1.fileName.substring(0, MainFrame.mainFrame1.fileName.lastIndexOf("."));
                     extension = MainFrame.mainFrame1.fileName.substring(MainFrame.mainFrame1.fileName.lastIndexOf(".") + 1, MainFrame.mainFrame1.fileName.length());
                     parentdir = MainFrame.mainFrame1.filePath.substring(0, MainFrame.mainFrame1.filePath.lastIndexOf(System.getProperty("file.separator")));
                 } else {
                     name = MainFrame.mainFrame1.fileName;
                     extension = "dat";
                     parentdir = MainFrame.mainFrame1.filePath.substring(0, MainFrame.mainFrame1.filePath.lastIndexOf(System.getProperty("file.separator")));

                 }

                  String newfileName = name + "." + extension;

                 final String newfilepath = parentdir + System.getProperty("file.separator") + newfileName;

                 Runnable lookupData = new Runnable() {
                     public void run() {
                         SwingUtilities.invokeLater(new Runnable() {
                             public void run() {
                                 BitSet T = new BitSet(MainFrame.mainFrame1.MC.GetNUMSNPs());

                                 if (MainFrame.mainFrame1.jTabbedPane1.getSelectedIndex() >= 0) {
                                     ResultPanel rp = (ResultPanel) MainFrame.mainFrame1.jTabbedPane1.getSelectedComponent();

                                     T = rp.FI;
                 }
                                 MainFrame.mainFrame1.Parse.ExportData(newfilepath, T, Trans);
                             }
                         });
                     }
                 };
                 Thread lookupThread = new Thread(lookupData, "MyThread");
                 lookupThread.start();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
    }

    // Variables declaration - do not modify
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration

}
